# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  tagName: 'latest'
  imageName: 'activityreservation:$(tagName)'

steps:

- script: docker build -f Dockerfile -t $(imageName)
  displayName: 'Docker build Script'


